#
# Install basic packages from OS distro
#
FROM ubuntu:22.04 AS base

ARG PYTHON_VERSION=3.12

ENV DEBIAN_FRONTEND=noninteractive

RUN rm -f /etc/apt/apt.conf.d/docker-clean

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates curl libnuma-dev gnupg wget git nano \
        sudo libelf1 kmod file build-essential python3-dev \
        software-properties-common sqlite3 libsqlite3-dev libfmt-dev \
        libmsgpack-dev libsuitesparse-dev libdw-dev pkg-config libdrm-dev

# Python
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    if ! python3 --version | grep -q ${PYTHON_VERSION} ; then \
        add-apt-repository -y ppa:deadsnakes/ppa && apt-get update && \
        apt-get install -y python${PYTHON_VERSION} python${PYTHON_VERSION}-dev \
            python${PYTHON_VERSION}-venv python${PYTHON_VERSION}-lib2to3 python-is-python3 ; \
    fi

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1 && \
    update-alternatives --set python3 /usr/bin/python${PYTHON_VERSION} && \
    ln -sf /usr/bin/python${PYTHON_VERSION}-config /usr/bin/python3-config && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python${PYTHON_VERSION}

RUN wget -nv -O /tmp/cmake-3.26.4-linux-x86_64.tar.gz https://cmake.org/files/v3.26/cmake-3.26.4-linux-x86_64.tar.gz && \
    tar zfx /tmp/cmake-3.26.4-linux-x86_64.tar.gz -C /opt/ && \
    mv /opt/cmake-3.26.4-linux-x86_64 /opt/cmake-3.26.4 && \
    rm -f /tmp/cmake-3.26.4-linux-x86_64.tar.gz

ENV PATH=/opt/cmake-3.26.4/bin:$PATH

#
# Install ROCm deb packages
#
FROM base AS rocm_deb

ARG ROCM_VERSION=7.2.2
ARG GFX_ARCH=gfx950

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    curl -sL https://repo.radeon.com/rocm/rocm.gpg.key | apt-key add - && \
    printf "deb [arch=amd64] https://repo.radeon.com/rocm/apt/$ROCM_VERSION/ jammy main" | tee /etc/apt/sources.list.d/rocm.list && \
    printf "Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600\n" > /etc/apt/preferences.d/artifactory-pin-600 && \
    apt-get update && \
    apt-get install -y rocm && \
    find /opt/rocm/lib -type f -name '*gfx*' | grep -Ev "${GFX_ARCH}" | xargs rm -f && \
    find /opt/rocm/lib/hipblaslt/library -type f -name '*gfx*' | grep -Ev "${GFX_ARCH}" | xargs rm -f && \
    find /opt/rocm/lib/rocblas/library -type f -name '*gfx*' | grep -Ev "${GFX_ARCH}" | xargs rm -f && \
    find /opt/rocm/share/miopen/db -type f -name '*gfx*' | grep -Ev "${GFX_ARCH}" | xargs rm -f && \
    sqlite3 /opt/rocm/lib/rocfft/rocfft_kernel_cache.db "delete from cache_v1 where arch != '${GFX_ARCH}' ; vacuum"

ENV ROCM_HOME=/opt/rocm
ENV CPLUS_INCLUDE_PATH=/opt/rocm/include:
ENV LD_LIBRARY_PATH=/opt/rocm/lib:$LD_LIBRARY_PATH
ENV PATH=/opt/rocm/bin:/opt/rocm/llvm/bin:$PATH

#
# Install pytorch packages
#
FROM rocm_deb AS rocm_torch

ARG GFX_ARCH=gfx950

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip "setuptools<80" wheel numpy einops ninja && \
    pip install /opt/rocm/share/amd_smi

RUN --mount=type=cache,target=/root/.cache/pip \
    cd /tmp && \
    wget https://repo.radeon.com/rocm/manylinux/rocm-rel-7.2.2/torch-2.10.0+rocm7.2.2.lw.git40d237bf-cp312-cp312-linux_x86_64.whl && \
    wget https://repo.radeon.com/rocm/manylinux/rocm-rel-7.2.2/apex-1.10.0+rocm7.2.2.git751f5dd5-cp312-cp312-linux_x86_64.whl && \
    wget https://repo.radeon.com/rocm/manylinux/rocm-rel-7.2.2/torchaudio-2.10.0+rocm7.2.2.git5047768f-cp312-cp312-linux_x86_64.whl && \
    wget https://repo.radeon.com/rocm/manylinux/rocm-rel-7.2.2/torchvision-0.25.0+rocm7.2.2.git82df5f59-cp312-cp312-linux_x86_64.whl && \
    wget https://repo.radeon.com/rocm/manylinux/rocm-rel-7.2.2/triton-3.6.0+rocm7.2.2.git4ed88892-cp312-cp312-linux_x86_64.whl && \
    pip3 install /tmp/*.whl && \
    rm -f /tmp/*.whl

ENV PYTORCH_ROCM_ARCH=${GFX_ARCH}

#
# Build Flash Attention
#
FROM rocm_torch AS fa_build

ARG FA_REPO="https://github.com/ROCm/flash-attention"
ARG FA_TAG="b3ae496"
ARG GFX_ARCH=gfx950

RUN git clone ${FA_REPO}

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install numpy einops packaging psutil ninja \
 && cd flash-attention \
 && git checkout ${FA_TAG} \
 && git submodule init \
 && git submodule update \
 && GPU_ARCHS=${GFX_ARCH} BUILD_TARGET=rocm MAX_JOBS=$(nproc) python3 setup.py bdist_wheel \
 && mkdir /install && cp dist/*.whl /install

#
# Install Flash Attention
#
FROM rocm_torch AS install_fa

RUN --mount=type=bind,from=fa_build,source=/install,target=/tmp/install \
    --mount=type=cache,target=/root/.cache/pip \
    pip install /tmp/install/*.whl

#
# vLLLM
#
FROM install_fa AS vllm_dev

ARG AITER_REPO="https://github.com/ROCm/aiter"
#ARG AITER_BRANCH="28a7b6a"
ARG AITER_BRANCH="v0.1.10.post3"
ARG VLLM_REPO="https://github.com/vllm-project/vllm.git"
#ARG VLLM_BRANCH="66ed64f"
ARG VLLM_BRANCH="613238a"

ARG GFX_ARCH=gfx950
ARG COMMON_WORKDIR=/opt
ARG BUILD_RPD="1"

WORKDIR ${COMMON_WORKDIR}

RUN --mount=type=bind,source=.,target=/tmp/home \
    ls -l /tmp/home && \
    mkdir -p ${COMMON_WORKDIR}/aiter && \
    tar -xzf /tmp/home/aiter.tar.gz -C ${COMMON_WORKDIR}/aiter --strip-components=1 && \ 
    mkdir -p ${COMMON_WORKDIR}/vllm && \
    tar -xzf /tmp/home/vllm.tar.gz -C ${COMMON_WORKDIR}/vllm --strip-components=1 && \
    rm -rf ${COMMON_WORKDIR}/aiter/.git && \
    rm -rf ${COMMON_WORKDIR}/vllm/.git

RUN cd aiter && \
    pip install -r requirements.txt

RUN cd aiter && \
    GPU_ARCHS=${GFX_ARCH} python3 setup.py develop && \
    rm -rf /tmp/*


ENV VLLM_INSTALL_PUNICA_KERNELS=1

# The package name in ROCm 7.0.1 is 'triton', and in 7.0.0 and earlier is 'pytorch-triton'
# So we need to create a fake package if 'triton' is not found, to satisfy pip requirement
# during vLLM installation. 
RUN pip show triton > /dev/null 2>&1; \
    if [ "$?" -ne 0 ] ; then \
        cd $(pip show torch | grep Location | cut -d ' ' -f 2); \
        mkdir triton-3.99.0.dist-info ; \
        touch triton-3.99.0.dist-info/METADATA ; \
    fi

# Build vLLM
# Sometimes after vLLM installation, numpy is upgraded to 2.x but pandas is still at 2.0.3,
# so manually upgrade pandas to avoid numpy mismatch in aiter JIT phase.
RUN --mount=type=cache,target=/root/.cache/pip \
    cd vllm && \
    sed -i '/^\s*gpt-oss .*/d' requirements/common.txt && \
    sed -i '/triton/d' requirements/build/rocm.txt && \
    sed -i '/torch/d' requirements/build/rocm.txt && \
    sed -i '/amdsmi/d' requirements/build/rocm.txt && \
    sed -i '/^\s*\"torch/d' pyproject.toml && \
    pip install -U pandas tilelang && \
    ROCM_PATH=/opt/rocm pip install --no-binary :all: fastsafetensors && \
    pip install -r requirements/build/rocm.txt && \
    pip install -r requirements/rocm.txt && \
    python3 -m pip install -v --no-build-isolation -e .[fastsafetensors] && \
	rm -rf /tmp/*

RUN if [ ${BUILD_RPD} -eq "1" ]; then \
    git clone -b nvtx_enabled https://github.com/ROCm/rocmProfileData.git \
    && cd rocmProfileData/rpd_tracer \
    && pip install -r requirements.txt && cd ../ \
    && make && make install \
    && cd hipMarker && python3 setup.py install ; fi

#
# AITER JIT build
#
FROM vllm_dev AS vllm_jit_build

ARG COMMON_WORKDIR=/opt
ARG GFX_ARCH=gfx950

ENV GPU_ARCHS=${GFX_ARCH}

COPY <<EOF /tmp/aot.patch
--- /tmp/aot.py 2026-03-17 12:32:53.024315485 +0800
+++ aot.py      2026-03-17 12:33:09.925405034 +0800
@@ -122,7 +122,11 @@
         "module_mla_metadata",
         "module_mla_reduce",
         "module_mla_asm",
-        # "module_moe_ck2stages",
+        "module_gemm_common",
+        "module_gemm_a8w8_blockscale",
+        "module_moe_ck2stages",
+        "module_activation",
+        "module_fmha_v3_varlen_fwd",
     ]
     print(f"modules_to_build: {modules_to_build}")
     start_time = time.time()
@@ -181,6 +185,9 @@
                 "torch_exclude": build_args.get("torch_exclude", False),
             }
 
+            if "third_party" in build_module.__code__.co_varnames:
+                filtered_args["third_party"] = []
+
             if module_name == "module_mha_varlen_fwd":
                 # Build runtime variants explicitly
                 rt_module_names = [
EOF

RUN wget -O /${COMMON_WORKDIR}/aiter/aiter/aot/aot.py https://raw.githubusercontent.com/ROCm/aiter/c751255be974773f8f9f17e4ce6ba25ba9ca2404/aiter/aot/aot.py && \
    patch /${COMMON_WORKDIR}/aiter/aiter/aot/aot.py < /tmp/aot.patch && \
    rm -f /tmp/aot.patch

RUN python3 -m aiter.aot.aot --enable-parallel
 
#
# Install AITER JIT binaries
#
FROM vllm_dev AS vllm_jit

ARG COMMON_WORKDIR=/opt

COPY --from=vllm_jit_build /${COMMON_WORKDIR}/aiter/aiter/jit/*.so /${COMMON_WORKDIR}/aiter/aiter/jit/
COPY --from=vllm_jit_build /${COMMON_WORKDIR}/aiter/aiter/aot/aot.py /${COMMON_WORKDIR}/aiter/aiter/aot/aot.py

RUN cd $(pip show torch | grep Location | cut -d ' ' -f 2) && \
    rm -rf triton-3.99.0.dist-info

RUN --mount=type=bind,from=ubuntu:22.04,source=/,target=/tmp \
    cp /tmp/etc/apt/apt.conf.d/docker-clean /etc/apt/apt.conf.d/docker-clean

ENV DEBIAN_FRONTEND=

WORKDIR /root

